# SA gitlab-admin dans ns/gitlab-runner
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: gitlab-runner
---
# Role gitlab-admin dans ns/gitlab-runner
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gitlab-runner
  name: gitlab-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
# Role gitlab-admin-mtrg dans ns/mtrg
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mtrg
  name: gitlab-admin-mtrg
rules:
  - apiGroups: ["", "extensions","apps"]
    resources: ["*"]
    verbs: ["*"]
---
# Bind entre gitlab-runner/gitlab-admin et gitlab-admin
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-admin
  namespace: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-admin
  apiGroup: rbac.authorization.k8s.io
---
# Bind entre gitlab-runner/gitlab-admin et gitlab-admin-mtrg
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-admin-mtrg
  namespace: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-admin-mtrg
  apiGroup: rbac.authorization.k8s.io


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-admin-mtrg2
  namespace: mtrg
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-admin-mtrg
  apiGroup: rbac.authorization.k8s.io