apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |-
    concurrent = 1
    [[runners]]
      name = "test Gitlab Runner"
      url = "https://gitlab.com/ci"
      token = "*****************"
      executor = "kubernetes"

      # pre_clone_script = 'cat /etc/resolv.conf && nslookup google.de && wget http://google.de && cat index.html'

      [runners.cache]
        #Type = "s3"
        #Path = "gitlab-runner"
        #Shared = false
        [runners.cache.s3]
          #ServerAddress = "s3.amazonaws.com"
          #AccessKey = "<AccessKey>"
          #SecretKey = "<SecretKey>"
          #BucketName = "test"
          #BucketLocation = "eu-east-1"
          #Insecure = false
      [runners.kubernetes]
        namespace = "gitlab-runner"
        privileged = true
        poll_timeout = 600
        cpu_request = "500m"
        service_cpu_request = "50m"
        disable_cache = false
        shm_size = 0
        tls_verify = false
        [[runners.kubernetes.volumes.host_path]]
            name = "docker"
            mount_path = "/var/run/docker.sock"
            host_path = "/var/run/docker.sock"

        # Add the configuration below to run the runner in a dedicated nodegroup
        # [runners.kubernetes.node_tolerations]
          # "cicd" = "NoSchedule"
